from app.domain.exceptions.base import DomainError


class UserSettingsError(DomainError): ...


class InvalidThemeError(UserSettingsError): ...


class InvalidLocaleError(UserSettingsError): ...


class InvalidTimezoneError(UserSettingsError): ...


class InvalidPrivacyScopeError(UserSettingsError): ...


class UserSettingsNotFoundError(UserSettingsError): ...
